[package]
name = "exchange_place"
version = "0.0.1"
authors = [ "you",]
edition = "2021"

[lib]
path = "src/exchange-place.rs"

[dependencies.multiversx-sc]
version = "0.45.1"

[dev-dependencies.multiversx-sc-scenario]
version = "0.45.1"