[package]
name = "barterswap_meta"
version = "1.0.0"
edition = "2021"
publish = true
authors = [ "Multifungible"]

[dev-dependencies]

[dependencies.barterswap]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.45.1"


